[project]
name = "manman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.13.3",
    "fastapi>=0.115.4",
    "pika>=1.3.2",
    "psycopg2-binary>=2.9.10",
    "python-jose[cryptography]>=3.3.0",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.36",
    "sqlmodel>=0.0.22",
    "typer>=0.12.5",
    "uvicorn>=0.32.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pika-stubs>=0.1.3",
    "pre-commit>=4.0.1",
    "ruff>=0.7.1",
]


[tool.uv]
package = true
