[tool.poetry]
name = "manman"
version = "0.1.0"
description = ""
authors = ["qmastermoo <alex.harding@whale-net.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.3"
fastapi = "^0.110.2"
pika = "^1.3.2"
sqlalchemy = "^2.0.29"
alembic = "^1.13.1"
psycopg2-binary = "^2.9.9"
uvicorn = "^0.29.0"
sqlmodel = "^0.0.16"
requests = "^2.31.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.1"
pre-commit = "^3.7.0"
mypy = "^1.10.0"
pika-stubs = "^0.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
