"""empty message

Revision ID: 8a5cb751b177
Revises: 2d62be20d6bb
Create Date: 2024-04-27 18:19:24.204368

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a5cb751b177"
down_revision: Union[str, None] = "2d62be20d6bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_server_configs",
        sa.Column("name", sa.String(), nullable=True),
        schema="manman",
    )
    op.execute(
        "update manman.game_server_configs gsc set name = (select gs.name from manman.game_servers gs where gs.game_server_id = gsc.game_server_id limit 1)"
    )
    op.alter_column("game_server_configs", "name", nullable=False, schema="manman")
    op.drop_column("servers", "name", schema="manman")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "servers",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="manman",
    )
    op.drop_column("game_server_configs", "name", schema="manman")
    # ### end Alembic commands ###
