"""empty message

Revision ID: 7fb64ceb4da2
Revises: 3427e52b10ce
Create Date: 2025-05-18 19:49:41.124439

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fb64ceb4da2"
down_revision: Union[str, None] = "3427e52b10ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_server_configs",
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        schema="manman",
    )
    op.execute(
        "UPDATE manman.game_server_configs SET is_visible = true WHERE is_visible IS NULL"
    )
    op.alter_column(
        "game_server_configs",
        "is_visible",
        nullable=False,
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_server_configs", "is_visible", schema="manman")
    # ### end Alembic commands ###
