"""empty message

Revision ID: 997d31da4c5c
Revises: d5ce82ad21d2
Create Date: 2025-05-25 11:06:42.211577

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "997d31da4c5c"
down_revision: Union[str, None] = "d5ce82ad21d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_server_instances",
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_server_instances", "last_heartbeat", schema="manman")
    # ### end Alembic commands ###
