"""empty message

Revision ID: d5ce82ad21d2
Revises: 7fb64ceb4da2
Create Date: 2025-05-24 22:15:47.153231

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5ce82ad21d2"
down_revision: Union[str, None] = "7fb64ceb4da2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_info",
        sa.Column("class_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status_type",
            sa.Enum(
                "CREATED",
                "INITIALIZING",
                "RUNNING",
                "LOST",
                "COMPLETE",
                "CRASHED",
                name="statustype",
            ),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(), nullable=False),
        sa.Column("status_info_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Integer(), nullable=True),
        sa.Column("game_server_instance_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(worker_id IS NULL AND game_server_instance_id IS NOT NULL) OR (worker_id IS NOT NULL AND game_server_instance_id IS NULL)",
            name="chk_status_info_target_not_null",
        ),
        sa.ForeignKeyConstraint(
            ["game_server_instance_id"],
            ["manman.game_server_instances.game_server_instance_id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["manman.workers.worker_id"],
        ),
        sa.PrimaryKeyConstraint("status_info_id"),
        schema="manman",
    )
    op.create_index(
        op.f("ix_manman_status_info_game_server_instance_id"),
        "status_info",
        ["game_server_instance_id"],
        unique=False,
        schema="manman",
    )
    op.create_index(
        op.f("ix_manman_status_info_worker_id"),
        "status_info",
        ["worker_id"],
        unique=False,
        schema="manman",
    )
    op.create_index(
        "ix_status_info_as_of_game_server_instance_worker",
        "status_info",
        ["as_of", "game_server_instance_id", "worker_id"],
        unique=False,
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_status_info_as_of_game_server_instance_worker",
        table_name="status_info",
        schema="manman",
    )
    op.drop_index(
        op.f("ix_manman_status_info_worker_id"),
        table_name="status_info",
        schema="manman",
    )
    op.drop_index(
        op.f("ix_manman_status_info_game_server_instance_id"),
        table_name="status_info",
        schema="manman",
    )
    op.drop_table("status_info", schema="manman")
    # ### end Alembic commands ###
    op.execute("drop type statustype")
