"""empty message

Revision ID: 86b5da41e9f8
Revises: f22d61deac49
Create Date: 2025-03-16 00:59:46.966120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86b5da41e9f8"
down_revision: Union[str, None] = "f22d61deac49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_server_configs",
        sa.Column(
            "env_var", sa.ARRAY(sa.String()), nullable=False, server_default="{}"
        ),
        schema="manman",
    )
    # ### end Alembic commands ###
    op.alter_column(
        "game_server_configs", "env_var", server_default=None, schema="manman"
    )
    op.execute("""
    update manman.game_server_configs set env_var = '{LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH,SteamAppId=892970}'
    where game_server_id in (select game_server_id from manman.game_servers where name ='valheim')
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_server_configs", "env_var", schema="manman")
    # ### end Alembic commands ###
