"""empty message

Revision ID: 3427e52b10ce
Revises: 86b5da41e9f8
Create Date: 2025-05-05 18:54:53.419091

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3427e52b10ce"
down_revision: Union[str, None] = "86b5da41e9f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_server_instances",
        sa.Column("worker_id", sa.Integer(), nullable=True),
        schema="manman",
    )
    op.create_index(
        op.f("ix_manman_game_server_instances_worker_id"),
        "game_server_instances",
        ["worker_id"],
        unique=False,
        schema="manman",
    )
    op.create_foreign_key(
        None,
        "game_server_instances",
        "workers",
        ["worker_id"],
        ["worker_id"],
        source_schema="manman",
        referent_schema="manman",
    )
    op.add_column(
        "workers",
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "last_heartbeat", schema="manman")
    op.drop_constraint(
        None, "game_server_instances", schema="manman", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_manman_game_server_instances_worker_id"),
        table_name="game_server_instances",
        schema="manman",
    )
    op.drop_column("game_server_instances", "worker_id", schema="manman")
    # ### end Alembic commands ###
