# Production-like configuration with higher replicas
image:
  name: "ghcr.io/whale-net/manman"
  tag: "v1.2.0"

namespace: manman

apis:
  experience:
    enabled: true
    name: manman-experience
    replicas: 3
    port: 8000
    command: "start-experience-api"

  workerDal:
    enabled: true
    name: manman-worker-dal
    replicas: 2
    port: 8000
    command: "start-worker-dal-api"

  status:
    enabled: true
    name: manman-status
    replicas: 2
    port: 8000
    command: "start-status-api"

processors:
  status:
    enabled: true
    name: manman-status-processor
    replicas: 2
    command: "start-status-processor"

ingress:
  enabled: true
  name: "manman-ingress"
  host: "api.manman.example.com"
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    configs:
      - secretName: manman-tls-prod
        hosts:
          - api.manman.example.com

migrations:
  skip_migration: false
  timeout: 600

env:
  rabbitmq:
    port: 5672
    host: "prod-rabbitmq.example.com"
    user: "manman-prod"
    password: "super-secure-password"
    enable_ssl: true
    ssl_hostname: "prod-rabbitmq.example.com"
  app_env: production
  db:
    url: "postgresql+psycopg2://manman:secure-password@prod-db.example.com:5432/manman_prod"
