"""empty message

Revision ID: 2d62be20d6bb
Revises: ebef1cd30fd9
Create Date: 2024-04-27 18:13:24.874368

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d62be20d6bb"
down_revision: Union[str, None] = "ebef1cd30fd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "servers",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "servers",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="manman",
    )
    # ### end Alembic commands ###
