"""empty message

Revision ID: 28f0f4545d5e
Revises: 9d2c57a933ef
Create Date: 2024-04-27 15:24:22.727289

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "28f0f4545d5e"
down_revision: Union[str, None] = "9d2c57a933ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "server_types", ["server_type"], schema="manman")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "server_types", schema="manman", type_="unique")
    # ### end Alembic commands ###
