"""empty message

Revision ID: b47437d75324
Revises: 81201ed06b73
Create Date: 2024-04-27 19:21:53.748523

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b47437d75324"
down_revision: Union[str, None] = "81201ed06b73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_server_instances",
        sa.Column("game_server_instance_id", sa.Integer(), nullable=False),
        sa.Column("game_server_config_id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_server_config_id"],
            ["manman.game_server_configs.game_server_config_id"],
        ),
        sa.PrimaryKeyConstraint("game_server_instance_id"),
        schema="manman",
    )
    op.create_index(
        op.f("ix_manman_game_server_instances_game_server_config_id"),
        "game_server_instances",
        ["game_server_config_id"],
        unique=False,
        schema="manman",
    )
    op.drop_index(
        "ix_manman_servers_game_server_config_id", table_name="servers", schema="manman"
    )
    op.drop_table("servers", schema="manman")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column(
            "game_server_instance_id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('manman.servers_game_sever_instance_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "game_server_config_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_server_config_id"],
            ["manman.game_server_configs.game_server_config_id"],
            name="servers_game_server_config_id_fkey",
        ),
        sa.PrimaryKeyConstraint("game_server_instance_id", name="servers_pkey"),
        schema="manman",
    )
    op.create_index(
        "ix_manman_servers_game_server_config_id",
        "servers",
        ["game_server_config_id"],
        unique=False,
        schema="manman",
    )
    op.drop_index(
        op.f("ix_manman_game_server_instances_game_server_config_id"),
        table_name="game_server_instances",
        schema="manman",
    )
    op.drop_table("game_server_instances", schema="manman")
    # ### end Alembic commands ###
