"""empty message

Revision ID: 81201ed06b73
Revises: 8a5cb751b177
Create Date: 2024-04-27 18:49:05.998764

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81201ed06b73"
down_revision: Union[str, None] = "8a5cb751b177"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ixu_game_server_configs_game_server_id_name",
        "game_server_configs",
        ["game_server_id", "name"],
        unique=True,
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ixu_game_server_configs_game_server_id_name",
        table_name="game_server_configs",
        schema="manman",
    )
    # ### end Alembic commands ###
