"""empty message

Revision ID: 793f88201df6
Revises: 5f6ffaa4b629
Create Date: 2024-04-27 17:46:09.714843

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "793f88201df6"
down_revision: Union[str, None] = "5f6ffaa4b629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ixu_game_server_app_id_server_type",
        "game_servers",
        ["app_id", "server_type"],
        unique=True,
        schema="manman",
    )
    op.create_index(
        "ixu_game_server_name_server_type",
        "game_servers",
        ["name", "server_type"],
        unique=True,
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ixu_game_server_name_server_type", table_name="game_servers", schema="manman"
    )
    op.drop_index(
        "ixu_game_server_app_id_server_type", table_name="game_servers", schema="manman"
    )
    # ### end Alembic commands ###
