"""empty message

Revision ID: 9d2c57a933ef
Revises:
Create Date: 2024-04-27 15:02:10.710116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from manman.worker.server import ServerTypeEnum
from manman.models import ServerType as ServerTypeTable

# revision identifiers, used by Alembic.
revision: str = "9d2c57a933ef"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # apparently this isn't automatic
    op.execute("create schema if not exists manman")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "server_type", sa.Enum("STEAM", name="servertypeenum"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="manman",
    )
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="manman",
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=15), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="manman",
    )
    # ### end Alembic commands ###

    # data migration
    # this could use the create_table above but doing this for future reference
    op.bulk_insert(
        ServerTypeTable.__table__, [{"server_type": ServerTypeEnum.STEAM.name}]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workers", schema="manman")
    op.drop_table("servers", schema="manman")
    op.drop_table("server_types", schema="manman")
    # ### end Alembic commands ###
    op.execute("drop type manman.servertypeenum")
