"""fix

Revision ID: 809ff0ead878
Revises: b47437d75324
Create Date: 2024-04-28 15:20:51.588647

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "809ff0ead878"
down_revision: Union[str, None] = "b47437d75324"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workers",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="manman",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workers",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="manman",
    )
    # ### end Alembic commands ###
