[tool.poetry]
name = "manman-test_shared"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "manman", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
