# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-dev
spec:
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: rabbitmq-management-port
      port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app: rabbitmq-dev
