{{- if .Values.apis.experience.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apis.experience.name }}-{{ .Values.env.app_env }}-service
  namespace: {{ .Values.namespace }}
  labels:
    component: experience-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.apis.experience.name }}-{{ .Values.env.app_env }}
  ports:
    - protocol: TCP
      port: {{ .Values.apis.experience.port }}
      targetPort: {{ .Values.apis.experience.port }}
      name: http
{{- end }}
