{{- if .Values.apis.experience.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apis.experience.name }}-{{ .Values.env.app_env }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.apis.experience.name }}-{{ .Values.env.app_env }}
    component: experience-api
  annotations:
    # Ensure this deploys after migrations complete
    "argocd.argoproj.io/sync-wave": "0"
spec:
  replicas: {{ .Values.apis.experience.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apis.experience.name }}-{{ .Values.env.app_env }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.apis.experience.name }}-{{ .Values.env.app_env }}
        component: experience-api
    spec:
      containers:
        - name: manman-experience-api
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: {{ .Values.apis.experience.port }}
              name: http
          args:
            - host
            - {{ .Values.apis.experience.command }}
            # Migrations run as pre-install hook, so skip the migration check
            - --no-should-run-migration-check
          livenessProbe:
            httpGet:
              path: /host/health
              port: {{ .Values.apis.experience.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # TODO - improve how secrets are sourced in this template
          env:
            - name: MANMAN_POSTGRES_URL
              value: {{ .Values.env.db.url }}
            - name: MANMAN_RABBITMQ_HOST
              value: {{ .Values.env.rabbitmq.host }}
            - name: MANMAN_RABBITMQ_PORT
              value: {{ .Values.env.rabbitmq.port | quote }}
            - name: MANMAN_RABBITMQ_USER
              value: {{ .Values.env.rabbitmq.user }}
            - name: MANMAN_RABBITMQ_PASSWORD
              value: {{ .Values.env.rabbitmq.password }}
            - name: MANMAN_RABBITMQ_ENABLE_SSL
              value: {{ .Values.env.rabbitmq.enable_ssl | quote }}
            - name: MANMAN_RABBITMQ_SSL_HOSTNAME
              value: {{ .Values.env.rabbitmq.ssl_hostname | quote }}
            - name: APP_ENV
              value: {{ .Values.env.app_env }}
{{- end }}
