{{- if not .Values.migrations.skip_migration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: manman-migrations-{{ .Values.env.app_env }}-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
  labels:
    app: manman-migrations
    component: migration
  annotations:
    # Helm hooks to run this job before deployments
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    # ArgoCD specific annotations
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
    "argocd.argoproj.io/sync-wave": "-1"
spec:
  # Ensure the job doesn't run in parallel
  parallelism: 1
  completions: 1
  backoffLimit: 3
  # Add timeout for ArgoCD (5 minutes should be enough for most migrations)
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: manman-migrations
        component: migration
      annotations:
        # Prevent ArgoCD from managing this pod directly
        "argocd.argoproj.io/compare-options": IgnoreExtraneous
    spec:
      restartPolicy: Never
      containers:
        - name: manman-migrations
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          args:
            - host
            - run-migration
          env:
            - name: MANMAN_POSTGRES_URL
              value: {{ .Values.env.db.url }}
            - name: MANMAN_RABBITMQ_HOST
              value: {{ .Values.env.rabbitmq.host }}
            - name: MANMAN_RABBITMQ_PORT
              value: {{ .Values.env.rabbitmq.port | quote }}
            - name: MANMAN_RABBITMQ_USER
              value: {{ .Values.env.rabbitmq.user }}
            - name: MANMAN_RABBITMQ_PASSWORD
              value: {{ .Values.env.rabbitmq.password }}
            - name: MANMAN_RABBITMQ_ENABLE_SSL
              value: {{ .Values.env.rabbitmq.enable_ssl | quote }}
            - name: MANMAN_RABBITMQ_SSL_HOSTNAME
              value: {{ .Values.env.rabbitmq.ssl_hostname | quote }}
            - name: APP_ENV
              value: {{ .Values.env.app_env }}
{{- end }}
