apiVersion: v1
kind: Service
metadata:
  name: manman-host-{{ .Values.env.app_env }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: manman-host-{{ .Values.env.app_env }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
