{{- if .Values.processors.status.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.processors.status.name }}-{{ .Values.env.app_env }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.processors.status.name }}-{{ .Values.env.app_env }}
    component: status-processor
  annotations:
    # Ensure this deploys after migrations complete
    "argocd.argoproj.io/sync-wave": "0"
spec:
  replicas: {{ .Values.processors.status.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.processors.status.name }}-{{ .Values.env.app_env }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.processors.status.name }}-{{ .Values.env.app_env }}
        component: status-processor
    spec:
      containers:
        - name: manman-status-processor
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          args:
            - host
            - {{ .Values.processors.status.command }}
            # Migrations run as pre-install hook, so skip the migration check
            - --no-should-run-migration-check
          # No health check needed for processors - they're not HTTP services
          env:
            - name: MANMAN_POSTGRES_URL
              value: {{ .Values.env.db.url }}
            - name: MANMAN_RABBITMQ_HOST
              value: {{ .Values.env.rabbitmq.host }}
            - name: MANMAN_RABBITMQ_PORT
              value: {{ .Values.env.rabbitmq.port | quote }}
            - name: MANMAN_RABBITMQ_USER
              value: {{ .Values.env.rabbitmq.user }}
            - name: MANMAN_RABBITMQ_PASSWORD
              value: {{ .Values.env.rabbitmq.password }}
            - name: MANMAN_RABBITMQ_ENABLE_SSL
              value: {{ .Values.env.rabbitmq.enable_ssl | quote }}
            - name: MANMAN_RABBITMQ_SSL_HOSTNAME
              value: {{ .Values.env.rabbitmq.ssl_hostname | quote }}
            - name: APP_ENV
              value: {{ .Values.env.app_env }}
{{- end }}
