image:
  name: "ghcr.io/whale-net/manman"
  tag: ""

namespace: manman

# Configuration for which APIs to deploy
apis:
  # Experience API (host layer)
  experience:
    enabled: true
    name: manman-experience
    replicas: 1
    port: 8000
    command: "start-experience-api"

  # Worker DAL API
  workerDal:
    enabled: true
    name: manman-worker-dal
    replicas: 1
    port: 8000
    command: "start-worker-dal-api"

# Migration configuration
migrations:
  # Set to true to skip running migrations entirely
  skip_migration: false
  # Timeout for migration job in seconds (5 minutes)
  timeout: 300

# ArgoCD specific configuration
argocd:
  # Sync timeout for the entire application (10 minutes)
  syncTimeout: 600
  # Retry configuration
  retry:
    limit: 3
    backoff:
      duration: 30s
      factor: 2
      maxDuration: 3m

env:
  rabbitmq:
    port: 5672
    host: <rabbitmq_host>
    user: <rabbitmq_user>
    password: <rabbitmq_password>
    enable_ssl: false
    ssl_hostname: <rabbitmq_ssl_hostname>
  # change this to the environment you are deploying to
  app_env: dev

  db:
    url: <postgresql+psycopg2://user:password@host:port/database>
#  otelCollector:
#    logs:
#      endpoint: <logs_endpoint>
#    traces:
#      endpoint: <traces_endpoint>
#    metrics:
#      endpoint: <metrics_endpoint>
