image:
  name: "ghcr.io/whale-net/manman"
  tag: ""

namespace: manman

deployment:
  name: manman-host-deployment
  replicas: 1

env:
  db:
    url: <postgresql+psycopg2://user:password@host:port/database>
#  otelCollector:
#    logs:
#      endpoint: <logs_endpoint>
#    traces:
#      endpoint: <traces_endpoint>
#    metrics:
#      endpoint: <metrics_endpoint>
